name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'  # README 파일 변경을 무시
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
